workflows:
  smartlists-workflow:
    name: SmartLists Workflow
    scripts:
        - name: Build SmartLists
          script: xcodebuild build -project "SmartLists.xcodeproj" -scheme "SmartLists" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO