workflows:
  smartlists-workflow:
    name: SmartLists Workflow
    environment:
      xcode: 14.0
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: develop
          include: true
      cancel_previous_builds: true
    scripts:
        - name: Build SmartLists
          script: xcodebuild build -project "SmartLists.xcodeproj" -scheme "SmartLists" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        - name: iOS test
          script: |
            xcode-project run-tests \
                --project SmartLists.xcodeproj \
                --scheme SmartLists \
                --device "iPhone 12"
    publishing:
      email:
        recipients:
          - fabiolfp@gmail.com
      slack:
        channel: '#codemagic'
        notify_on_build_start: true