workflows:
  smartlists-workflow:
    name: SmartLists Workflow
    environment:
      xcode: 14.0
    scripts:
        - name: Build SmartLists
          script: xcodebuild build -project "SmartLists.xcodeproj" -scheme "SmartLists" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        - name: iOS test
          script: |
            xcode-project run-tests \
                --project SmartLists.xcodeproj \
                --scheme SmartLists \
                --device "iPhone 12"
                --test-only=/SmartLists/SmartListsTests
    publishing:
      email:
        recipients:
          - fabiolfp@gmail.com